export const SPECS = {
  'BASE-1': {
    id: 'BASE-1',
    title: 'Aesthetic 2.24',
    family: 'shipped baseline',
    move: 'Current instrument-panel restraint translated into the future gallery.',
    essence:
      'Ink, registers, hairlines, square geometry, and one restrained accent.',
    dna: ['single-scale hierarchy', 'hairline structure', 'status on glyph'],
    dials: {
      color: 'accent and categorical hues',
      type: 'mono ratio only',
      density: 'measure and shell density',
      shape: 'fixed square geometry',
      imagery: 'technical pen-and-ink subject',
    },
    layout: 'rail',
    componentLayout: 'grid',
    button: {
      grammar: 'ink block / hairline plate',
      height: '2.45rem',
      padding: '0 1rem',
      weight: '650',
      primary: 'ink fill, paper label',
      secondary: 'paper fill, hairline edge',
      ghost: 'ink only, no edge until focus',
      destructive: 'danger edge, danger label',
      focus: '2px accent outline, 2px offset',
      pressed: 'inset rule, no scale change',
      loading: 'static spinner, stable width',
    },
    tokens: {
      fontDisplay: 'Geist, ui-sans-serif, system-ui, sans-serif',
      fontBody: 'Geist, ui-sans-serif, system-ui, sans-serif',
      fontMono: '"Geist Mono", ui-monospace, monospace',
      radiusSm: '0px',
      radiusMd: '0px',
      radiusLg: '0px',
      border: '1px',
      shadow: 'none',
      space: 1,
      control: '2.45rem',
      light: {
        canvas: '#fcfcfc',
        surface: '#fcfcfc',
        raised: '#f3f3f3',
        ink: '#151515',
        muted: '#686868',
        line: '#e2e2e2',
        accent: '#2643d0',
        accentInk: '#ffffff',
        success: '#2f7d57',
        warning: '#a76519',
        danger: '#b53a36',
      },
      dark: {
        canvas: '#121212',
        surface: '#121212',
        raised: '#1b1b1b',
        ink: '#ededed',
        muted: '#a0a0a0',
        line: '#303030',
        accent: '#8c9eff',
        accentInk: '#10121a',
        success: '#73c69d',
        warning: '#e5aa61',
        danger: '#ef817c',
      },
    },
    products: {
      canary: {
        accent: '#d14b3f',
        secondary: '#f0b3aa',
        note: 'urgent · compact · signal-led',
      },
      powder: {
        accent: '#4969d8',
        secondary: '#b8c5f4',
        note: 'dense · operational · queue-led',
      },
      crucible: {
        accent: '#8a52c7',
        secondary: '#d2b8eb',
        note: 'analytical · experimental · evidence-led',
      },
      landmark: {
        accent: '#2f7d57',
        secondary: '#a9d8bf',
        note: 'editorial · public · release-led',
      },
    },
    css: '.future-root .type-display{font-size:1em}.future-root .type-title{font-size:1em}.future-root .type-body{font-size:1em}',
  },
};
