export default [
  {
    id: 'CARRY-QR',
    title: 'Quiet Register',
    family: 'carried favorite',
    move: 'A ruled public record: narrow index, broad working measure, exact action plates.',
    essence: 'The page is a record you can operate, not a stack of cards.',
    layout: 'register',
    statusStyle: 'register-tick',
    statusNote:
      'A ruled stem changes its terminal cut; color touches only the terminal.',
    tokens: {
      light: {
        canvas: '#f5f3ed',
        surface: '#fbfaf6',
        wash: '#efede6',
        ink: '#171815',
        muted: '#66685f',
        line: '#d4d2ca',
        accent: '#2643d0',
        success: '#2f7654',
        warning: '#9b651a',
        danger: '#a33c37',
      },
      dark: {
        canvas: '#111210',
        surface: '#151613',
        wash: '#1b1d19',
        ink: '#eeeeea',
        muted: '#a5a79e',
        line: '#34362f',
        accent: '#8c9eff',
        success: '#78c49c',
        warning: '#e0a85e',
        danger: '#ee817b',
      },
    },
    css: '.site.layout-register .studio{grid-template-columns:8rem minmax(0,1fr)}.site.layout-register .studio:before{content:"PUBLIC RECORD / 005";font:700 10px var(--mono);letter-spacing:.09em;border-right:1px solid var(--line);padding:1rem;color:var(--muted)}.site.layout-register .offer,.site.layout-register .work-list{padding-inline:clamp(1rem,5vw,5rem)}',
  },
  {
    id: 'CARRY-CF',
    title: 'Civic Folio',
    family: 'carried favorite',
    move: 'A public-facing technical folio with broad margins and authoritative bands.',
    essence: 'Institutional clarity without institutional coldness.',
    layout: 'folio',
    statusStyle: 'corner-mark',
    statusNote:
      'Open corners show state by closure and direction, never by a generic symbol.',
    tokens: {
      light: {
        canvas: '#f4f1e9',
        surface: '#fcfbf7',
        wash: '#eeece5',
        ink: '#191a17',
        muted: '#676960',
        line: '#d0cec5',
        accent: '#3153c5',
        success: '#367658',
        warning: '#9a681d',
        danger: '#a6433d',
      },
      dark: {
        canvas: '#121310',
        surface: '#171814',
        wash: '#1e201b',
        ink: '#efefe9',
        muted: '#a6a89e',
        line: '#373930',
        accent: '#93a4ff',
        success: '#79c49e',
        warning: '#dfa95f',
        danger: '#ef8580',
      },
    },
    css: '.site.layout-folio .page{max-width:72rem;margin:auto;border-inline:1px solid var(--line)}.site.layout-folio .offer{padding:clamp(2rem,7vw,7rem)}.site.layout-folio .work-list{border-top:3px double var(--ink)}.site.layout-folio .work-row{grid-template-columns:2rem 10rem 1fr}',
  },
];
